"""empty message

Revision ID: 3fff990fdb04
Revises: 951226363062
Create Date: 2016-12-29 03:30:11.891000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fff990fdb04'
down_revision = '951226363062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'grades_timestamp_key', 'grades', type_='unique')
    op.drop_column('grades', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'grades_timestamp_key', 'grades', ['timestamp'])
    # ### end Alembic commands ###
