"""empty message

Revision ID: 4f391f2b03c2
Revises: df1bd296326d
Create Date: 2016-12-24 00:57:46.225000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f391f2b03c2'
down_revision = 'df1bd296326d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'parents', 'telephone')
    op.add_column(u'parents', sa.Column('telephone', sa.String(length=50), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #
    pass
    # ### end Alembic commands ###
