"""empty message

Revision ID: 850b98b61e5e
Revises: e2f4f9920a62
Create Date: 2016-12-13 22:59:31.367000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850b98b61e5e'
down_revision = 'e2f4f9920a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),

    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
