"""empty message

Revision ID: 951226363062
Revises: ed276291117f
Create Date: 2016-12-29 03:20:06.420000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951226363062'
down_revision = 'ed276291117f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'grades', ['timestamp'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='unique')
    op.drop_column('grades', 'timestamp')
    # ### end Alembic commands ###
