"""empty message

Revision ID: a5eb9368bfd6
Revises: 2381f510c943
Create Date: 2016-12-14 18:11:38.223000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb9368bfd6'
down_revision = '2381f510c943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'students', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column(u'students', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'students', 'name')
    op.drop_column(u'students', 'email')
    op.drop_table('grades')
    # ### end Alembic commands ###
