"""empty message

Revision ID: ab3a857687b6
Revises: 4f391f2b03c2
Create Date: 2016-12-25 14:24:28.836000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3a857687b6'
down_revision = '4f391f2b03c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parents', ['telephone'])
    op.add_column(u'parents', sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='unique')
    # ### end Alembic commands ###
