"""empty message

Revision ID: b1a018e2a9d2
Revises: ad8cfd1da72f
Create Date: 2016-12-16 12:13:00.553000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a018e2a9d2'
down_revision = 'ad8cfd1da72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(u'users', sa.Column('school', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'students', 'school')
    # op.create_table('grades',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('studentId', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['studentId'], [u'students.id'], name=u'grades_studentId_fkey'),
    # sa.PrimaryKeyConstraint('id', name=u'grades_pkey')
    # )
    # op.create_table('group',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('group_id_seq'::regclass)"), nullable=False),
    # sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], name=u'group_owner_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name=u'group_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('users_id_seq'::regclass)"), nullable=False),
    # sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'users_pkey'),
    # sa.UniqueConstraint('email', name=u'users_email_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('students',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['group_id'], [u'group.id'], name=u'students_group_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name=u'students_pkey')
    # )
    # ### end Alembic commands ###
