"""empty message

Revision ID: b333ca011fea
Revises: b1a018e2a9d2
Create Date: 2016-12-16 21:49:59.514000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b333ca011fea'
down_revision = 'b1a018e2a9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_to_students',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.add_column(u'grades', sa.Column('grade', sa.Integer(), nullable=False))
    op.add_column(u'grades', sa.Column('name', sa.Integer(), nullable=True))
    op.add_column(u'grades', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'grades_studentId_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'])
    op.drop_column(u'grades', 'studentId')
    op.add_column(u'group', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column(u'students', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'students_group_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['teacher_id'], ['id'])
    op.drop_column(u'students', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'students', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(u'students_group_id_fkey', 'students', 'group', ['group_id'], ['id'])
    op.drop_column(u'students', 'teacher_id')
    op.drop_column(u'group', 'name')
    op.add_column(u'grades', sa.Column('studentId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(u'grades_studentId_fkey', 'grades', 'students', ['studentId'], ['id'])
    op.drop_column(u'grades', 'student_id')
    op.drop_column(u'grades', 'name')
    op.drop_column(u'grades', 'grade')
    op.drop_table('group_to_students')
    # ### end Alembic commands ###
