"""empty message

Revision ID: df1bd296326d
Revises: 1a4075e3c316
Create Date: 2016-12-23 19:34:56.127000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1bd296326d'
down_revision = '1a4075e3c316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    op.add_column(u'parents', sa.Column('email', sa.String(length=50),
                                        nullable=False))
    op.create_unique_constraint(None, 'parents', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email', 'students', type_='unique')
    op.drop_constraint('email', 'parents', type_='unique')
    # ### end Alembic commands ###
