"""empty message

Revision ID: ed276291117f
Revises: a0929773a5e7
Create Date: 2016-12-28 20:01:19.793000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed276291117f'
down_revision = 'a0929773a5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_to_students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_to_students',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], [u'group.id'], name=u'group_to_students_group_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], [u'students.id'], name=u'group_to_students_student_id_fkey')
    )
    # ### end Alembic commands ###
